// <auto-generated />
using System;
using EmployeePortal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeePortal.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200702123041_EmployeePortal-V1.1")]
    partial class EmployeePortalV11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeePortal.Models.DepartmentModel", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentAddress");

                    b.Property<string>("DepartmentName");

                    b.HasKey("DepartmentId");

                    b.ToTable("DepartmentModels");
                });

            modelBuilder.Entity("EmployeePortal.Models.EmployeeModel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .IsRequired();

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeModels");
                });

            modelBuilder.Entity("EmployeePortal.Models.HumanResourceModel", b =>
                {
                    b.Property<int>("HrId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId1");

                    b.Property<string>("HrAddress");

                    b.Property<string>("HrName");

                    b.HasKey("HrId");

                    b.HasIndex("DepartmentId1");

                    b.ToTable("HumanResourceModels");
                });

            modelBuilder.Entity("EmployeePortal.Models.HumanResourceModel", b =>
                {
                    b.HasOne("EmployeePortal.Models.DepartmentModel", "DepartmentId")
                        .WithMany()
                        .HasForeignKey("DepartmentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
