var text1="               Welcome  to keval";
var text2="kiniyara";
console.log(text1.length);
var text3=text1.indexOf("to");
console.log(text3);
var text4=text1.lastIndexOf("rahul");
console.log(text4);
var text5=text1.lastIndexOf("keval");
console.log(text5);
var text6=text1.lastIndexOf("rahul",14);
console.log(text6);
var text7=text1.search("keval");
console.log(text7);
var text8=text1.slice(1,8);
console.log(text8);
var text9=text1.substring(4,10);
console.log(text9);
var text10=text1.substr(8,6);
console.log(text10);
var text11=text1.replace("rahul","keval");
console.log(text11);
var text12=text1.toLowerCase();
console.log(text12);
var text13=text1.toUpperCase();
console.log(text13);
var text14=text1.concat(text2);
console.log(text14);
var text15=text1.trim();
console.log(text15);
var text16=text1.charAt(15);
console.log(text16);
var text17=text1.charCodeAt(15);
console.log(text17);
var text18="a,b,c,d,e,f";
var arr=text18.split(   ",");
console.log(arr[3]);